# Generated by Django 3.1.2 on 2020-11-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, choices=[('0', 'Historical'), ('1', 'Very Good'), ('2', 'Good'), ('3', 'Moderate'), ('4', 'Bad'), ('5', 'Very Bad'), ('6', 'Destroyed'), ('7', 'Unknown')], max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
                ('monument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='marker', serialize=False, to='map.monument')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='map.monument')),
            ],
        ),
    ]
