# Generated by Django 3.1.2 on 2020-11-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('photos', models.CharField(blank=True, max_length=1024)),
                ('coords', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
